date.timezone = Asia/Tehran
default_charset = UTF-8
memory_limit = 768M
max_execution_time = 600
max_input_time = 600
upload_max_filesize = 512M
post_max_size = 520M
max_file_uploads = 5
display_errors = Off
log_errors = On
expose_php = Off
session.cookie_httponly = On
session.cookie_secure = On
session.cookie_samesite = Strict
